# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tadas Gedgaudas
title: Software Developer
email: tadasgedgaudas@icloud.com
website: https://tadasgedgaudas.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: JustADude404
github_username:  tadasgedgaudas
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: tadas-gedgaudas-01a0a7132
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Software developer with experience in working with small and medium-sized teams. 

  Programming languages I am most skilled with: <mark>Python</mark>, <mark>Typescript</mark>, <mark>Golang</mark> (learning)
  Databases: <mark>MySQL</mark>, <mark>MongoDB</mark>, <mark>PostgreSQL</mark>

  <mark>Web3</mark> is my passion and I keep learning about it every day!

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Multifarm
        link: https://www.multifarm.fi/
        # link_text: boringcompany.com
        sub_title: Lead Developer
        caption: June 2022 - Present
        description: | # this will include new lines to allow paragraphs
            Python developer. Mostly working with Web3 technologies as well as taking care of infrastructure. 
    content:
      - layout: left
        title: Multifarm
        link: https://www.multifarm.fi/
        # link_text: boringcompany.com
        sub_title: Lead Developer
        caption: June 2022 - Present
        description: | # this will include new lines to allow paragraphs
            Python developer. Mostly working with Web3 technologies as well as taking care of infrastructure. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LCC International University
        caption: 2014 - 2018
        sub_title: Business Administration & Theology

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Sports (weight lifting)
      - Gaming
      - Buying domains and never deploying my personal projects

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
