# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tadas Gedgaudas
title: Software Developer
email: tadasgedgaudas@icloud.com
website: https://tadasgedgaudas.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: JustADude404
github_username:  tadasgedgaudas
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: tadas-gedgaudas-01a0a7132
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: |
  Software developer with experience in working with small and medium-sized teams. 

  Programming languages I am most skilled with: <mark>Python</mark>, <mark>Typescript</mark>, <mark>Golang</mark> (learning), <mark>PhP</mark> (no longer coding)
  
  Databases: <mark>MySQL</mark>, <mark>MongoDB</mark>, <mark>PostgreSQL</mark>

  Infrastructure: <mark>Kubernetes</mark> and it's tools (Helm, Docker)

  <mark>Web3</mark> is my passion and I keep learning about it every day!

content:

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Multifarm
        link: https://www.multifarm.fi/
        sub_title: Lead Developer
        caption: June 2022 - Present
        description: |
            Python developer. Mostly working with Web3 technologies as well as taking care of infrastructure. 

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Oxylabs
        link: https://oxylabs.io/
        sub_title: Python Developer
        caption: June 2020 - June 2022
        description: |
            Working in a larger team and using Python to solve various issues.
  
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Dokunetas
        link: http://www.dokunetas.net
        sub_title: Junior Developer
        caption: May 2016 - Jul 2018
        description: |
            First job as a developer. Worked with PhP. Developed small web crawlers as well as small web applications.
  
  - title: Education
    layout: list
    content:
      - layout: left
        title: Software Development Academy
        caption: 2019 - 2020
        sub_title: Java Developer Bootstrap Courses

  - title: Education
    layout: list
    content:
      - layout: left
        title: LCC International University
        caption: 2014 - 2018
        sub_title: Business Administration & Theology

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Sports (weight lifting)
      - Gaming
      - Buying domains and never deploying my personal projects

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
